/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consulta)'}/appointmentDetails` | `/appointmentDetails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consulta)'}/examsHistory` | `/examsHistory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consulta)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consulta)'}/scheduledAppointments` | `/scheduledAppointments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consulta)'}/scheduledExams` | `/scheduledExams`; params?: Router.UnknownInputParams; } | { pathname: `${'/(financeiro)'}/details` | `/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(financeiro)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(financeiro)'}/itemDetails` | `/itemDetails`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(consulta)'}/appointmentDetails` | `/appointmentDetails`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(consulta)'}/examsHistory` | `/examsHistory`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(consulta)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(consulta)'}/scheduledAppointments` | `/scheduledAppointments`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(consulta)'}/scheduledExams` | `/scheduledExams`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(financeiro)'}/details` | `/details`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(financeiro)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(financeiro)'}/itemDetails` | `/itemDetails`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(consulta)'}/appointmentDetails${`?${string}` | `#${string}` | ''}` | `/appointmentDetails${`?${string}` | `#${string}` | ''}` | `${'/(consulta)'}/examsHistory${`?${string}` | `#${string}` | ''}` | `/examsHistory${`?${string}` | `#${string}` | ''}` | `${'/(consulta)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(consulta)'}/scheduledAppointments${`?${string}` | `#${string}` | ''}` | `/scheduledAppointments${`?${string}` | `#${string}` | ''}` | `${'/(consulta)'}/scheduledExams${`?${string}` | `#${string}` | ''}` | `/scheduledExams${`?${string}` | `#${string}` | ''}` | `${'/(financeiro)'}/details${`?${string}` | `#${string}` | ''}` | `/details${`?${string}` | `#${string}` | ''}` | `${'/(financeiro)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(financeiro)'}/itemDetails${`?${string}` | `#${string}` | ''}` | `/itemDetails${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consulta)'}/appointmentDetails` | `/appointmentDetails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consulta)'}/examsHistory` | `/examsHistory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consulta)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consulta)'}/scheduledAppointments` | `/scheduledAppointments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consulta)'}/scheduledExams` | `/scheduledExams`; params?: Router.UnknownInputParams; } | { pathname: `${'/(financeiro)'}/details` | `/details`; params?: Router.UnknownInputParams; } | { pathname: `${'/(financeiro)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(financeiro)'}/itemDetails` | `/itemDetails`; params?: Router.UnknownInputParams; };
    }
  }
}
